config/routes.rb
Rails.application.routes.draw do
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'application#index'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'
  resources :users

  get 'notes' => 'notes#show'
  get 'notes/new' => 'notes#new'
  post 'notes/new' => 'notes#create'

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # RElationships
  has_many :notes, dependent: :destroy
  # Callbacks
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

# Validation
  validates :name, presence: true, length: {maximum: 20}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, 
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }, allow_blank: true

  has_secure_password

  # Returns the hash digest of the given string
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost

    BCrypt::Password.create(string, cost: cost)
  end

  # Generates random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Rmembers a token stored for a particular user in the database
  def remember 
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if remember_token supplied matches the digest
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets remembered users
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  layout 'index'
  protect_from_forgery with: :exception
  include SessionsHelper

  def home
  end

  def index
    if logged_in?
      redirect_to notes_url
    else
      render 'layouts/homepage'
    end
  end

  private
  # Before filters
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in to continue"
      redirect_to login_url
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  layout 'application'
  before_action :logged_in_user, only: [:show, :new]

  def show
    @notes = current_user.notes
  end

  def new
    @note = Note.new
    render 'notes/_notesform'
  end

  def create
    # @note = Note.new(note_params)
    @note = current_user.notes.build(note_params)
    if @note.save
      flash[:success] = "Note successfully created"
      redirect_to notes_url
    else
      flash.now[:danger] = "An error occured somewhere"
      render 'show'
    end
  end

  def index
    
  end

  private
    def note_params
      params.require(:note).permit(:content, :category)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'index'
  
  def new
    redirect_to notes_url if logged_in?
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
      flash[:success] = "You have successfully logged in"
      redirect_back_or notes_url
    else
      flash.now[:danger] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    flash[:success] = "You have successfully logged out" 
    redirect_to login_url
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    redirect_to notes_url if logged_in?
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'application'
  before_action :logged_in_user, only: [:edit, :update] 
  before_action :correct_user, only: [:edit, :update] 

  def index
    redirect_to edit_user_path(current_user)
  end

  def new
    if logged_in?
      redirect_to notes_url
    end
    @user = User.new 
     render 'new', :layout => 'index'

  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Go-Notes #{@user.name}"
      redirect_to @user
    else
      render 'new'
    end    
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile successfully updated"
      redirect_to @user
    else
      flash[:danger] = "Error: profile couldn't be updated. Please try again"
      render 'edit'
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_url unless current_user?(@user)
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Go-Notes"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  def active_link_to(icon_name, link_text, link_path, options={})
    options[:class] = 'active' if current_page?(link_path)
    link_to "#{image_tag(icon_name, class: 'img-responsive', alt: 'link_text', title: 'link_text', size: '68')} <span>#{link_text}</span>".html_safe, link_path, options
  end
end

app/helpers/notes_helper.rb
module NotesHelper
  
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs user in
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers user until user logs out
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Forgets users the moment the user logs out
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Sets the current user
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if user is the current user
  def current_user?(user)
    current_user == user
  end

  # Returns true if a user is logged in
  def logged_in?
    !current_user.nil?
  end

  # Logs user out
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location or to the default
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if logged_in? %>
    <aside class="sidebar">
      <ul>
        <li class="logo"><%= link_to image_tag("go-notes-logo-new.png", alt: "Go-Notes", class: "img-responsive", size: "160"), root_path %></li>
      </ul>
      
        <ul>
          <li class="menu-title">User Menu</li>
          <li><%= active_link_to "sticky-note.png", "Notes", notes_path %></li>
          <li><%= active_link_to "profile-setting.png", "Profile Settings", edit_user_url(current_user) %></li>
          <li><%= active_link_to "logout.png", "Logout", logout_path, method: :delete %></li>
        </ul>
        <ul>
          <li class="menu-title">Write New Note</li>
        </ul>
        <%= render 'notes/notesform' %>
    </aside>
  <% end %>
  <section class="main-container fade in">
    <div class="top">
      
    </div>
      <%= yield %>
    <div class="col-md-12"><%= debug(params) if Rails.env.development? %></div>
  </section>
</body>
</html>

app/views/layouts/homepage.html.erb
<!-- Header -->
    <header>
        <div class="container">
            <div class="intro-text">
                <div class="intro-lead-in">Welcome To Go-Notes!</div>
                <div class="intro-heading">Take Your Notes With You</div>
                <%= link_to "Get Started Here", signup_path, class: "page-scroll btn btn-xl" %>
            </div>
        </div>
    </header>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= full_title(yield(:title)) %></title>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" class="index">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to image_tag("go-notes-logo-new.png", alt: "Go-Notes", class: "img-responsive home-logo", size: "260"), root_path %>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <%= link_to "about", about_path, class: "page-scroll" %>
                    </li>
                    <li>
                        <%= link_to "sign in", login_path, class: "page-scroll" %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    <%= yield %>
</body>

</html>

app/views/notes/_note.html.erb
  <div class="li" id="notes-<%= note.id %>">
    <p><%= "#{note.content} - #{note.category}" %></p>
  </div>
  

app/views/notes/_notesform.html.erb
<div class="note-form">

  <%= form_for(:note, url: notes_new_path) do |f| %>
    <%= f.label :content %>
    <%= f.text_area :content, placeholder: "Compose your note...", size:"2x5", class: "form-control" %>

    <%= f.label :category %>
    <%= f.text_field :category, placeholder: "give it a category...", class: "form-control" %>
    <%= f.submit "Post Note" , class: "btn btn-primary" %>
  <% end %>
</div>

app/views/notes/show.html.erb
<% if @notes.nil? %>
  <%= render 'notes/notesform'  %>
<% else %>
  <div class="content">
    <% @notes.group_by(&:category).each do |cat, note| %> 
      <div id="notes">
      <% cat = 'uncategorized' if cat.empty? %>
        <div class="title">#<%= cat %></div>
          <div class="ul">
            <%= render note %>
          </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class=" col-md-4 row form-container">
      <% flash.each do |msg_type, msg| %>
        <div class="alert alert-<%= msg_type %>"><%= msg %></div>
      <% end %>
  <h2>About Page</h2>
  <p>About Go-Notes</p>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class=" col-md-4 row form-container">
  <% flash.each do |msg_type, msg| %>
    <div class="alert alert-<%= msg_type %>"><%= msg %></div>
  <% end %>
  <h2>Contact us Page</h2>
  <p>Contact the Go-Notes team @teamGoNotes</p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<div class=" col-md-4 row form-container">
  <% flash.each do |msg_type, msg| %>
    <div class="alert alert-<%= msg_type %>"><%= msg %></div>
  <% end %>
  <h1>Need Help?</h1>
  <p>If you need help in using Go-Notes here are the faqs related to using Go-Notes</p>
</div>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <h1>Go-Notes</h1>
    <p>Create and keep Notes on the Go. Need to store an idea somewhere on the move? Go-Notes is here for ya!</p>
  </body>
</html>

app/views/users/_form.html.erb
<%= render "shared/error_messages" %>
<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>

<%= f.label :email %>
<%= f.email_field :email, class: 'form-control' %>

<%= f.label :password %>
<%= f.password_field :password, class: 'form-control' %>

<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation, class: 'form-control' %>

app/views/users/edit.html.erb
<% provide(:title, "Edit profile") %>

<div role="tabpanel">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Profile</a></li>
    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
  <!-- Profile tab content -->
    <div role="tabpanel" class="clear-fix tab-pane fade in active" id="profile"> 
      <div class="row">
        <%= form_for(@user) do |f| %>
        <div class="col-md-4 col-md-offset-3">
          <h1>Edit your profile</h1>
          <p>You can edit your profile below</p>
            <%= render 'form', f: f %>
        </div>
        <div class="col-md-3 left">
          <div class="gravatar_edit col-md-offset-2">
            <%= gravatar_for @user %>
            <a href="http://gravatar.com/emails" target="_blank" class="btn btn-info btn-sm">change</a>
          </div>
        </div>
        <div class="col-md-4 col-md-offset-5"><%= f.submit "Save changes", class: "btn btn-primary col-md-4" %></div>
        <% end %>
      </div>
    </div>
    <!-- Settings tab content -->
    <div role="tabpanel" class="tab-pane fade clear-fix " id="settings">
      <div class="col-md-6 col-md-offset-2">
        <h1>Notes Settings</h1>
        <p>Settings for your notes goes here</p>
      </div>
    </div>
  </div>

</div>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<div class=" col-md-4 row form-container">
  <% flash.each do |msg_type, msg| %>
    <div class="alert alert-<%= msg_type %>"><%= msg %></div>
  <% end %>
  <h1>Sign up</h1>
  <p>This is the sign up page for new users</p>
  <%= form_for(@user) do |f| %>
    <%= render 'form', f: f %>
    <%= f.submit "Create my account", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>